sudo: false # use container-based build
language: python
notifications:
    email: false

matrix:
  fast_finish: true
  include:
  - python: 3.5
    env: CONDA_ENV=py35


before_install:
  install:
  - conda env create --file ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  - source ci/rbm_install_utils
  - f2py_leap
  # scipy should not have been installed, but it's included in older versions of
  # the conda pandas package
  - python setup.py install
