site_name: RBM
site_description: River Basin Model
site_author: UW Hydro | Computational Hydrology
#repo_url: https://github.com/UW-Hydro/RBM
repo_url: https://github.com/YifanCheng/RBM/tree/develop
# Not sure about the site_url,theme_dir or site_favicon
site_url: http://rbm_yifan.readthedocs.org/
theme: readthedocs
#theme_dir: 'docs/custom_rtd_theme'
#site_favicon: vic_favicon.jpg
copyright: 2016
docs_dir: docs
site_dir: site
use_directory_urls: true

pages:
# Main pages
- Home: 'index.md'
- About:
    - 'Model Overview': 'Overview/ModelOverview.md'
    - 'References': 'Documentation/References.md'
    - 'FAQ': 'FAQ/FAQ.md'
    - 'Contact': 'contact.md'
    - 'Links': 'links.md'
- Documentation:
    - 'Tutorial':   'Documentation/tutorial.md'
    - 'How to run RBM (Salmon River example)': 'Documentation/run_RBM.md'
- Development:
    - 'Development': 'Development/ModelDevelopment.md'
    - 'Release Notes': 'Development/ReleaseNotes.md'
- Downloads:
    - Datasets: 'Datasets/Datasets.md'
    - Code: 'SourceCode/Code.md'

markdown_extensions:
    - toc:
        permalink: True
    - admonition:
    - fenced_code:

copyright: 'Copyright &copy; 2015, <a href="http://uw-hydro.github.io/">University of Washington Computational Hydrology Group</a>.'

#google_analytics: ['UA-65965729-1', 'vic.readthedocs.org']
