#!/usr/bin/env bash

set -e

mkdir ${TRAVIS_BUILD_DIR}/rbm/test_function

function install_miniconda {
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create --file $HOME/ci/requirements-py35.yml
  - source activate test_env
  - source $HOME/ci/rbm_install_utils
  # scipy should not have been installed, but it's included in older versions of
  # the conda pandas package
  - python $HOME/setup.py install
}

function f2py_leap {
  echo f2py_leap_year
  cd ${TRAVIS_BUILD_DIR}/src
  f2py -c -m leapyear Leap_Year.f90
  mv leapyear* ${TRAVIS_BUILD_DIR}/rbm/test_function
}

function rbm_script {
    echo rbm_script
    cd ${TRAVIS_BUILD_DIR}/src
    make
}

function rbm_after_success {
  echo rbm_after_success
  echo "rbm build succeeded"
}

function rbm_after_failure {
  echo rbm_after_failure
  echo "rbm build failed"
}
