#!/usr/bin/env bash

function rbm_script {
    echo rbm_script
    cd ${TRAVIS_BUILD_DIR}/src
    which gfortran
    make &> make.log
}

function rbm_after_success {
  echo rbm_after_success
  echo "rbm build succeeded"
}

function rbm_after_failure {
  echo rbm_after_failure
  echo "rbm build failed"
}
